name: Update Status

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Display the commit message
        run: echo 'New commit made: ${{ github.event.head_commit.message }}'
